name: gnegnolios-branding-budgie

description: |
  Budgie desktop branding (dconf overrides) for GnegnoliOS.

version: "0.1"

enabled: true

build: true

desktop: budgie

install:
  iso: true
  repository: true

dependencies:
  - gnegnolios-branding-common

build_system: makepkg
