name: gnegnolios-branding-mate

description: |
  MATE desktop branding (dconf overrides) for GnegnoliOS.

version: "0.1"

enabled: true

build: true

desktop: mate

install:
  iso: true
  repository: true

dependencies:
  - gnegnolios-branding-common

build_system: makepkg
