---
modules-search:
- local
instances:
- id: usage_profiles
  module: packagechooser
  config: packagechooser-usage_profiles.conf
- id: browsers
  module: packagechooser
  config: packagechooser-browsers.conf
- id: office_suites
  module: packagechooser
  config: packagechooser-office_suites.conf
- id: multimedia
  module: packagechooser
  config: packagechooser-multimedia.conf
- id: development_languages
  module: packagechooser
  config: packagechooser-development_languages.conf
- id: containers
  module: packagechooser
  config: packagechooser-containers.conf
- id: virtualization
  module: packagechooser
  config: packagechooser-virtualization.conf
- id: snapshots
  module: packagechooser
  config: packagechooser-snapshots.conf
- id: shells
  module: packagechooser
  config: packagechooser-shells.conf
- id: terminals
  module: packagechooser
  config: packagechooser-terminals.conf
- id: editors
  module: packagechooser
  config: packagechooser-editors.conf
- id: themes
  module: packagechooser
  config: packagechooser-themes.conf
- id: optional_services
  module: packagechooser
  config: packagechooser-optional_services.conf
- id: privacy
  module: packagechooser
  config: packagechooser-privacy.conf
- id: extra_tools
  module: packagechooser
  config: packagechooser-extra_tools.conf
- id: kernel
  module: packagechooser
  config: packagechooser-kernel.conf
- id: drivers
  module: packagechooser
  config: packagechooser-drivers.conf
- id: bootloader
  module: packagechooser
  config: packagechooser-bootloader.conf
- id: partition
  module: partition
  config: partition-advanced.conf
- id: bootloader
  module: bootloader
  config: bootloader-advanced.conf
sequence:
- show:
  - welcome
  - locale
  - keyboard
  - packagechooser@usage_profiles
  - packagechooser@browsers
  - packagechooser@office_suites
  - packagechooser@multimedia
  - packagechooser@development_languages
  - packagechooser@containers
  - packagechooser@virtualization
  - packagechooser@snapshots
  - packagechooser@shells
  - packagechooser@terminals
  - packagechooser@editors
  - packagechooser@themes
  - packagechooser@optional_services
  - packagechooser@privacy
  - packagechooser@extra_tools
  - packagechooser@kernel
  - packagechooser@drivers
  - packagechooser@bootloader
  - partition
  - users
  - summary
- exec:
  - partition
  - mount
  - unpackfs
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - users
  - displaymanager
  - networkcfg
  - hwclock
  - services-systemd
  - packages
  - initcpio
  - grubcfg
  - bootloader
  - umount
- show:
  - finished
branding: gnegnolios
prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: true
hide-back-and-next-during-exec: true
