name: gnegnolios-branding-cinnamon

description: |
  Cinnamon desktop branding (dconf overrides) for GnegnoliOS.

version: "0.1"

enabled: true

build: true

desktop: cinnamon

install:
  iso: true
  repository: true

dependencies:
  - gnegnolios-branding-common

build_system: makepkg
