# ==========================================================
# GnegnoliOS Calamares Unpackfs
# ==========================================================

---
unpack:
  - source: "/run/archiso/bootmnt/gnegnolios/x86_64/airootfs.sfs"
    sourcefs: "squashfs"
    destination: ""
