# ==========================================================
# GnegnoliOS Distribution Manifest
# ==========================================================

name: GnegnoliOS
id: gnegnolios
version: "0.1-alpha"

base:
  distro: archlinux
  architecture: x86_64

branding:
  name: GnegnoliOS
  codename: Genesis

kernel:
  default: linux
  available:
    - linux
    - linux-lts
    - linux-zen

desktop:
  default: kde
  available:
    - kde
    - gnome
    - hyprland
    - unity

filesystem:
  default: btrfs
  available:
    - btrfs
    - ext4

package_manager:
  default: pacman

additional_package_managers:
  - paru
  - flatpak

repositories:
  - gnegnolios-core

profiles:
  - gaming
  - development
  - office
