name: gnegnolios-release

description: |
  Base release package for GnegnoliOS.

version: "0.1"

enabled: true

build: true

install:
  iso: true
  repository: true

dependencies: []

build_system: makepkg
