[Theme]
GtkTheme=GnegnoliOS
IconTheme=GnegnoliOS
CursorTheme=GnegnoliOS
FontFamily=Inter
MonoFontFamily=JetBrains Mono

[Background]
Path=/usr/share/wallpapers/GnegnoliOSGenesis/contents/images/1536x1024.png
