name: gnegnolios-branding-xfce

description: |
  XFCE desktop branding (xfconf channels) for GnegnoliOS.

version: "0.1"

enabled: true

build: true

desktop: xfce

install:
  iso: true
  repository: true

dependencies:
  - gnegnolios-branding-common

build_system: makepkg
