name: gnegnolios-branding

description: |
  Branding package for GnegnoliOS.

version: "0.1"

enabled: true

build: true

install:
  iso: true
  repository: true

dependencies:
  - gnegnolios-release

build_system: makepkg
