[GnegnoliOS]
Theme=NERV
Desktop=KDE Plasma 6
Wallpaper=/usr/share/backgrounds/gnegnolios/evangelion-desktop.png

[Top]
Type=KDE Plasma Panel
Position=Top
Height=34
Floating=true

[Bottom]
Type=Krema
Position=Bottom
Alignment=Center
Style=Acrylic
Accent=Crimson
Zoom=Parabolic

[Terminal]
Ghostty=UNCHANGED
