[GnegnoliOS]
Theme=NERV
Desktop=KDE Plasma 6.7.5

[TopPanel]
Position=top
Style=taskbar
Height=38

[BottomDock]
Position=bottom
Style=floating
Height=62
Alignment=center

[Terminal]
Ghostty=untouched
